"""empty message

Revision ID: a5a5d5a7b1c9
Revises: 9d4c8adad175
Create Date: 2023-05-18 16:50:51.379218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a5d5a7b1c9'
down_revision = '9d4c8adad175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valores_diario', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    with op.batch_alter_table('valores_mensual', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valores_mensual', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('valores_diario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
