"""empty message

Revision ID: b47ff2c7ccee
Revises: a66150483a36
Create Date: 2023-04-13 15:26:52.793566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47ff2c7ccee'
down_revision = 'a66150483a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('estatura', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configue')
    # ### end Alembic commands ###
